# Site settings
title: Alex Sanchez-Stern
email: alexss@eng.ucsd.edu
description: > # this means to ignore newlines until "baseurl:"
  A website describing me and my work.
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "https://www.alexsanchezstern.com" # the base hostname & protocol for your site
github_username:  HazardousPeach
exclude: [Makefile]
css: [/bootstrap/css/bootstrap.min.css, /css/style.css]

# Build settings
markdown: kramdown
